import SkillImg from "../components/SkillImg";
import {
  Astro,
  Css,
  Express,
  Firebase,
  Html,
  JavasScript,
  MySql,
  Node,
  React,
  Svelte,
  Tailwind,
  Vite,
  Vue,
  WebComponents,
} from "../components/svg";

export const technologicalSkills = [
  {
    id: 1,
    href: "https://i.pinimg.com/564x/90/18/53/90185367541f87c6f16add8574714efe.jpg",
    name: "U E Castelldefels",
    fill: "#F7D800",
    Component: (props) => SkillImg(props),
  },
  {
    id: 2,
    href: "https://www.lapreferente.com/imagenes/escudos/escudo-6834.jpg?f=1436738400",
    name: "C F Ciudad Cooperativa",
    fill: "#CFE627",
    Component: (props) => SkillImg(props),
  },
  {
    id: 3,
    href: "https://files.fcf.cat/escudos/clubes/escudos/00100_0000967696_00100_0000948994_CF._PALLEJA.png.jpeg",
    name: "C F Pallejà",
    fill: "red",
    Component: (props) => SkillImg(props),
  },
  {
    id: 4,
    href: "https://www.lapreferente.com/imagenes/escudos/escudo-3567.jpg?f=1436738400",
    name: "C F Sta Eulàlia",
    fill: "#29A5D1",
    Component: (props) => SkillImg(props),
  },
  {
    id: 5,
    href: "http://www.lafutbolteca.com/wp-content/uploads/2010/08/Escudo-Futbol-Club-Santboi%C3%A0.jpg",
    name: "F C Santboià",
    Component: (props) => SkillImg(props),
  },
  {
    id: 6,
    href: "https://www.celh.es/wp-content/uploads/2022/02/Escut-CELH.jpg",
    name: "U E L´Hospitalet",
    fill: "#F73C00",
    Component: (props) => SkillImg(props),
  },
  {
    id: 7,
    href: "https://lirp.cdn-website.com/edefbfc8/dms3rep/multi/opt/logo+blanc-132h.png",
    name: "C D Fontsanta Fatjó",
    fill: "#3FB27F",
    Component: (props) => SkillImg(props),
  },
  {
    id: 8,
    href: "https://pbs.twimg.com/profile_images/951211097503272960/54dQZ_Z6_400x400.jpg",
    name: "C F Sant Andreu de la Barca",
    fill: "black",
    Component: (props) => SkillImg(props),
  },
  {
    id: 9,
    href: "https://pbs.twimg.com/profile_images/679595052511956992/zOTWgR-Z_400x400.jpg",
    name: "Sant Ignasi C E",
    Component: (props) => SkillImg(props),
  },
  {
    id: 10,
    href: "https://yt3.googleusercontent.com/FQTbGcYQTyMj90YdQUlK_9Y5EUvy7lQi09GHBUlWUC7ugT20sakw6lmhkNDT8apZMdjYF2Icwg=s160-c-k-c0x00ffffff-no-rj",
    name: "T K Soccer Academy",
    fill: "black",
    Component: (props) => SkillImg(props),
  },
];
