import {
  Astro,
  Css,
  Express,
  Firebase,
  Html,
  JavasScript,
  MySql,
  Node,
  React,
  Svelte,
  Tailwind,
  Vite,
  Vue,
  WebComponents,
} from "../components/svg";

export const technologicalSkills = [
  {
    id: 1,
    href: "https://developer.mozilla.org/es/docs/Web/JavaScript",
    name: "JavasScript",
    fill: "#F7D800",
    Component: (props) => JavasScript(props),
  },
  {
    id: 2,
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Web_components",
    name: "WebComponents",
    fill: "#CFE627",
    Component: (props) => WebComponents(props),
  },
  {
    id: 3,
    href: "https://developer.mozilla.org/es/docs/Web/HTML",
    name: "Html",
    fill: "red",
    Component: (props) => Html(props),
  },
  {
    id: 4,
    href: "https://developer.mozilla.org/es/docs/Web/CSS",
    name: "Css",
    fill: "#29A5D1",
    Component: (props) => Css(props),
  },
  {
    id: 5,
    href: "https://es.react.dev/",
    name: "React",
    Component: (props) => React(props),
  },
  {
    id: 6,
    href: "https://svelte.dev/",
    name: "Svelte",
    fill: "#F73C00",
    Component: (props) => Svelte(props),
  },
  {
    id: 7,
    href: "https://vuejs.org/",
    name: "Vue",
    fill: "#3FB27F",
    Component: (props) => Vue(props),
  },
  {
    id: 8,
    href: "https://astro.build/",
    name: "Astro",
    fill: "black",
    Component: (props) => Astro(props),
  },
  {
    id: 9,
    href: "",
    name: "Vite",
    Component: (props) => Vite(props),
  },
  {
    id: 10,
    href: "https://tailwindcss.com/",
    name: "Tailwind",
    fill: "black",
    Component: (props) => Tailwind(props),
  },
  {
    id: 11,
    href: "https://nodejs.org/en/",
    name: "Node",
    fill: "#7EC727",
    Component: (props) => Node(props),
  },
  {
    id: 12,
    href: "https://expressjs.com/es/",
    name: "Express",
    fill: "black",
    Component: (props) => Express(props),
  },
  {
    id: 13,
    href: "https://firebase.google.com",
    name: "Firebase",
    stroke: "orange",
    Component: (props) => Firebase(props),
  },
  {
    id: 14,
    href: "https://www.mysql.com/",
    name: "MySql",
    stroke: "black",
    Component: (props) => MySql(props),
  },
];
